name: Publish to Maven-central

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "**.md"
      - "**.MD"
      - ".idea/**"
  workflow_dispatch:

jobs:
  publish-to-maven-central:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Compile Java file
        run: javac src/HelloWorld.java

      - name: Run Java program
        run: java -cp src HelloWorld

      - name: build project
        run: |
          echo building 1 ...
          echo building 2 ...
          echo building 3 ...
          echo built finished!

      - name: publish to maven central
        run: |
          echo publishing to maven central
          echo published!